Default: &defaults
  database: andon.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: andon_test.sqlite3
  <<: *defaults

Staging:
  database: andon_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: andon_production.sqlite3
  poolsize: 100
  <<: *defaults
